capitales = [
    {"1": "Buenos Aires"},
    {"2": "San Salvador de Jujuy"},
    {"3": "Salta"},
    {"4": "San Miguel de Tucuman"},
    {"5": "Santiago del Estero"},
    {"6": "Formosa"},
    {"7": "Resistencia"},
    {"8": "Santa Fe"},
    {"9": "Corrientes"},
    {"10": "Posadas"},
    {"11": "Parana"},
    {"12": "Cordoba"},
    {"13": "La Rioja"},
    {"14": "San Juan"},
    {"15": "San Luis"},
    {"16": "Catamarca"},
    {"17": "Mendoza"},
    {"18": "Santa Rosa"},
    {"19": "Neuquen"},
    {"20": "Vietma"},
    {"21": "Rawson"},
    {"22": "Rio Gallegos"},
    {"23": "Ushuaia"}
]
